# Generated by Django 5.1.1 on 2024-09-22 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thelastriff', '0003_editora_remove_categoria_nome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editora',
        ),
    ]
